name: Build dist

on:
  pull_request:
    paths:
      - "package.json"
      - "bun.lockb"
      - "src/**"
      - "bin/**"
  push:
    branches:
      - "renovate/**"
    paths:
      - "package.json"
      - "bun.lockb"
      - "src/**"
      - "bin/**"

permissions:
  contents: read

# Cancel in-progress runs when a new run is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Rebuild dist
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for committing and pushing rebuilt dist

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          persist-credentials: true # zizmor: ignore[artipacked] Required for pushing commits

      - name: Install Bun
        uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2.1.2
        with:
          bun-version: 1.3.9

      - name: Install Task
        uses: go-task/setup-task@0ab1b2a65bc55236a3bc64cde78f80e20e8885c2 # v1.0.0
        with:
          repo-token: ${{ github.token }}
          version: "3.x"

      - name: Install dependencies
        run: task install

      - name: Build dist
        run: task build

      - name: Commit and push if changed
        run: |
          git config user.name "$USERNAME"
          git config user.email "$EMAIL"
          git add dist/
          git diff --staged --quiet || git commit --no-verify -m "chore: rebuild dist"
          git push
        env:
          USERNAME: github-actions[bot]
          EMAIL: github-actions[bot]@users.noreply.github.com
